Repository mizdra/eslint-interactive, pull requests merged in 2025-04, with the labels that each got.

#386 Require Node.js v20.19.0+
  .github/workflows/ci-node.yml
  package.json
Labels: Type: Breaking Change

#388 Use `util.parseArgs` instead of `yargs`
  package.json
  pnpm-lock.yaml
  src/cli/parse-argv.test.ts
  src/cli/parse-argv.ts
Labels: Type: Breaking Change

#390 Use `nanospinner` instead of `ora`
  e2e-test/flat-config/index.test.ts
  package.json
  pnpm-lock.yaml
  src/action/apply-suggestions.ts
  src/action/convert-error-to-warning-per-file.ts
  src/action/disable-per-file.ts
  src/action/disable-per-line.ts
  src/action/fix.ts
  src/action/make-fixable-and-fix.ts
  src/cli/ora.ts
  src/cli/spinner.ts
  src/scene/check-results.ts
  src/scene/lint.ts
Labels: Type: Refactoring

#391 feat: ESLint feature flags support
  README.md
  src/__snapshots__/core.test.ts.snap
  src/cli/parse-argv.test.ts
  src/cli/parse-argv.ts
  src/config.ts
  src/core.test.ts
Labels: Type: Feature

#392 Add bug report template
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
Labels: Type: Documentation

#394 Fix an incorrect description of `--format`
  README.md
  src/cli/parse-argv.ts
Labels: Type: Documentation

#393 Disable cache by default
  README.md
  src/cli/parse-argv.ts
  src/config.ts
Labels: Type: Breaking Change

#395 Replace `chalk` with `util.styleText`
  package.json
  pnpm-lock.yaml
  src/__snapshots__/core.test.ts.snap
  src/action/print-result-details.ts
  src/formatter/format-by-files.test.ts
  src/formatter/format-by-files.ts
  src/formatter/format-by-rules.ts
  src/formatter/index.test.ts
Labels: Type: Refactoring

#396 Require Node.js `^20.19.0 || >=22.12.0`
  README.md
  package.json
  src/action/print-result-details.ts
  src/formatter/format-by-files.ts
  src/formatter/format-by-rules.ts
Labels: Type: Breaking Change

#398 Execute pager without writing to file
  e2e-test/flat-config/index.test.ts
  src/cli/pager.ts
Labels: Type: Refactoring

#399 Do not use the `node_modules/.cache` directory as a temporary directory
  package.json
  pnpm-lock.yaml
  src/action/print-result-details.ts
  src/util/cache.ts
  src/util/file-system.ts
  src/util/filter-script.ts
Labels: Type: Refactoring

#400 Fix failure to write details of lint results to file
  e2e-test/flat-config/index.test.ts
  src/action/apply-suggestions.ts
  src/action/make-fixable-and-fix.ts
  src/action/print-result-details.ts
Labels: Type: Bug

#401 Project maintenance
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .gitignore
  .prettierignore
  .vscode/settings.json
  docs/programmable-api.md
  eslint.config.js
  example/eslint.config.mjs
  example/index.js
  example/lib/add-disable-comment.jsx
  example/lib/apply-suggestion.js
  example/lib/eslint-core-problem.mjs
  example/lib/make-fixable-and-fix.js
  example/lib/overlapped.js
  example/lib/shebang.js
  example/lib/sub.mjs
  example/lib/warning.js
  example/package.json
  example/rules/ban-exponentiation-operator.js
  package.json
  pnpm-lock.yaml
  src/core.test.ts
  src/test-util/fixtures.ts
  third-party/cachegrind-benchmarking/LICENSE
  third-party/cachegrind-benchmarking/cachegrind.py
  tsconfig.build.json
  tsconfig.json
  vite.config.base.ts
Labels: Type: Maintenance

#402 Implement an original table formatter
  package.json
  pnpm-lock.yaml
  src/__snapshots__/core.test.ts.snap
  src/formatter/format-by-rules.test.ts
  src/formatter/format-by-rules.ts
  src/formatter/format-table.test.ts
  src/formatter/format-table.ts
  src/formatter/index.test.ts
Labels: Type: Refactoring
